# Use postgres/example user/password credentials
version: '3.9'

services:
  tinyurl_app: 
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["sh","./start.sh"]
    volumes: 
      - .:/app

    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgressql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_HOST=${HOST}
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: