# Generated by Django 4.0.1 on 2022-01-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.CharField(max_length=50, verbose_name='Long URL'),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=50, unique=True, verbose_name='Short URL'),
        ),
    ]
