# Generated by Django 4.0.1 on 2022-01-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyapp', '0002_rename_user_id_url_user_alter_url_long_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.URLField(max_length=50, verbose_name='Long URL'),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.URLField(max_length=50, unique=True, verbose_name='Short URL'),
        ),
    ]
