# Generated by Django 4.0.1 on 2022-01-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyapp', '0005_alter_url_long_url_alter_url_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=6, unique=True, verbose_name='Short URL'),
        ),
    ]
