# Generated by Django 4.0.1 on 2022-01-30 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tinyapp', '0006_alter_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='slug_field',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
