# Generated by Django 4.0.1 on 2022-01-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyapp', '0006_alter_url_short_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=20)),
                ('short_url', models.CharField(max_length=6)),
                ('time_visited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='slug_field',
            field=models.SlugField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
