# Generated by Django 4.0.1 on 2022-01-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyapp', '0007_url_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='slug_field',
            field=models.SlugField(max_length=100),
        ),
    ]
