# Generated by Django 4.0.1 on 2024-07-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyapp', '0008_alter_url_long_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='slug_field',
            field=models.SlugField(max_length=5000),
        ),
    ]
